apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-static-pvc
  namespace: diving-into-k3s 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Mi
